import type { Metadata } from "next";
import { Keania_One } from "next/font/google";
import "./globals.css";

const inter = Keania_One({ 
  subsets: ["latin"],
  weight: ["400"]

 });

export const metadata: Metadata = {
  title: "Prix Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
